#### Numpy Hands-on practice

In [2]:
import numpy as np

In [3]:
a = [1,2,3]
a_array = np.array(a)
a_array

array([1, 2, 3])

In [4]:
print(a_array.ndim)
print(a_array.shape)

1
(3,)


In [5]:
b = [[1,2,3],[4,5,6]]
b_array = np.array(b)
b_array

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
print(b_array.ndim)
print(b_array.shape)

2
(2, 3)


In [9]:
# access element of array

b_array[1,2]

6

In [10]:
# array slicing
b_array[1:]

array([[4, 5, 6]])

In [12]:
# assgn or change the value of index in array

b_array[1,2] = 111

In [13]:
b_array

array([[  1,   2,   3],
       [  4,   5, 111]])

In [17]:
# 3-D array

c = [[[1,2],[3,4]],[[5,6],[7,8]]]
c_array = np.array(c)
c_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
print(c_array.ndim)
print(c_array.shape)

3
(1, 3, 3)


In [18]:
# accessing from 3-D
c_array[1,0,1]


6

In [20]:
# initialize array dirrectly

a_array = np.zeros(5)
a_array

array([0., 0., 0., 0., 0.])

In [21]:
# change the type

a_array = np.zeros(5,dtype=int)
a_array

array([0, 0, 0, 0, 0])

In [23]:
# creating array with dimensions

a_array = np.zeros((3,2))
a_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
a_array = np.ones((3,2))
a_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
a_array = np.full((3,2),10)
a_array

array([[10, 10],
       [10, 10],
       [10, 10]])

In [26]:
a_array = np.full((3,2),9999)
a_array

array([[9999, 9999],
       [9999, 9999],
       [9999, 9999]])

In [29]:
a_array = np.full((3,3,3),9999,dtype='int32')
a_array

array([[[9999, 9999, 9999],
        [9999, 9999, 9999],
        [9999, 9999, 9999]],

       [[9999, 9999, 9999],
        [9999, 9999, 9999],
        [9999, 9999, 9999]],

       [[9999, 9999, 9999],
        [9999, 9999, 9999],
        [9999, 9999, 9999]]], dtype=int32)

In [31]:
# create array of random decimal values

a_array = np.random.rand(2,3)
a_array

array([[0.62163609, 0.4429594 , 0.61063465],
       [0.67277169, 0.39751649, 0.51696127]])

In [32]:
# array of identity matrix

a_array = np.identity(5)
a_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a_array = np.identity(5,dtype=int)
a_array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [50]:
a_array_1 = np.identity(3,dtype=int)
a_array_1

a_array = np.identity(3,dtype=int)
a_array

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
a_array_1 = a_array

In [53]:
a_array_1[1,1] = 99

In [54]:
print(a_array)
print(a_array_1)

[[ 1  0  0]
 [ 0 99  0]
 [ 0  0  1]]
[[ 1  0  0]
 [ 0 99  0]
 [ 0  0  1]]


In [55]:
a_array_1 = a_array.copy()

In [56]:
a_array_1[1,1] = 999

In [57]:
print(a_array)
print(a_array_1)

[[ 1  0  0]
 [ 0 99  0]
 [ 0  0  1]]
[[  1   0   0]
 [  0 999   0]
 [  0   0   1]]


In [59]:
# add a number to all the elements of the array

a_array+2

array([[  3,   2,   2],
       [  2, 101,   2],
       [  2,   2,   3]])

In [60]:
# trigonometry

a_array = np.identity(3,dtype=int)
np.cos(a_array)

array([[0.54030231, 1.        , 1.        ],
       [1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 0.54030231]])

In [63]:
# statistics

a = [[1,2,3],[4,5,6],[7,8,9]]
a = np.array(a)
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
print(np.min(a,axis=0))
print(np.min(a,axis=1))
print(np.sum(a))

[1 2 3]
[1 4 7]
45


In [69]:
# rearange

print(a.reshape(1,9))
print(a.reshape(9,1))


[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [70]:
# stacking in numpy

a1 = np.full((2,3),9,dtype='int32')
a2 = np.full((2,3),5,dtype='int32')

In [73]:
a1,a2

(array([[9, 9, 9],
        [9, 9, 9]], dtype=int32),
 array([[5, 5, 5],
        [5, 5, 5]], dtype=int32))

In [75]:
np.vstack((a1,a2))

array([[9, 9, 9],
       [9, 9, 9],
       [5, 5, 5],
       [5, 5, 5]], dtype=int32)